name: Bug Report
description: Report a bug encountered while using Oblivion Desktop
body:
    - type: markdown
      attributes:
          value: |
              Please make sure to provide a descriptive report. It saves time for both the developers and users who are looking for solutions. Providing as much information as possible, including screenshots and logs, is highly appreciated. This will help us to better understand the issue and respond more effectively.

              لطفا مطمئن شوید که گزارشی تشریحی ارائه دهید. این باعث می‌شود که برنامه‌نویسان و کاربرانی که در جستجوی راهکارها هستند، زمان کمتری صرف کنند. ارائه اطلاعات بیشتر از جمله اسکرین‌شات و لاگ توصیه می‌شود. این باعث می‌شود که ما بهتر بتوانیم مشکل را درک کرده و به‌صورت بهتر پاسخ دهیم.
    - type: checkboxes
      id: confirm-search
      attributes:
          label: Search first | ابتدا جستجو کنید
          description: Please search [existing issues](https://github.com/bepass-org/oblivion-desktop/issues) before reporting.
          options:
              - label: I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد
                required: true
    - type: textarea
      id: problem
      attributes:
          label: What Happened? | چه اتفاقی افتاده؟
          description: |
              Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.
              لطفاً اطلاعات کاملی را ارائه دهید. اگر این کار را انجام ندهید، ممکن است مشکل شما به صورت تمام شده تلقی شده یا در زمان مناسبی بررسی نشود.
      validations:
          required: true
    - type: textarea
      id: reproduce
      attributes:
          label: Minimal Reproducible Example | چه پروسه‌ای برای مشاهده این مشکل طی کرده‌اید؟
          description: |
              Please tell us the steps to reproduce the bug. A [Minimal Reproducible Example (MRE)](https://stackoverflow.com/help/minimal-reproducible-example) is needed.
          placeholder: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. See error
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected Behavior | پروسه صحیح باید چگونه باشد؟
          description: |
              Please tell us what's the behavior you expect.
      validations:
          required: false
    - type: dropdown
      id: platform
      attributes:
          label: Platform/OS
          description: What platform are you seeing the problem on?
          multiple: true
          options:
              - Windows
              - macOS
              - Linux
              - Other
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output | لاگ برنامه
          description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
          render: shell
