blank_issues_enabled: false
contact_links:
    - name: FAQ
      url: https://github.com/bepass-org/oblivion-desktop/blob/main/FAQ.md
      about: Before asking a question or presenting a problem, read through the frequently asked questions.
