name: Publish

permissions: write-all

on:
    push:
        tags:
            - '*'

jobs:
    publish:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest, macos-13, macos-14]
                # os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v4

            - name: Install Node and NPM
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm

            - name: Install and build
              run: |
                  npm install
                  if [ "$RUNNER_OS" == "macOS" ]; then
                    npm install dmg-license
                  fi
                  npm run build
              shell: bash

            - name: Publish releases mac x64
              env:
                  # These values are used for auto updates signing
                  #   APPLE_ID: ${{ secrets.APPLE_ID }}
                  #   APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
                  #   CSC_LINK: ${{ secrets.CSC_LINK }}
                  #   CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
                  # This is used for uploading release assets to github
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: matrix.os == 'macos-13'
              run: npm exec electron-builder --mac dmg zip --x64 --publish always

            - name: Publish releases mac arm64
              env:
                  # These values are used for auto updates signing
                  #   APPLE_ID: ${{ secrets.APPLE_ID }}
                  #   APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
                  #   CSC_LINK: ${{ secrets.CSC_LINK }}
                  #   CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
                  # This is used for uploading release assets to github
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: matrix.os == 'macos-14'
              run: npm exec electron-builder --mac dmg zip --arm64 --publish always

            - name: Publish releases windows
              env:
                  # This is used for uploading release assets to github
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: matrix.os == 'windows-latest'
              run: npm exec electron-builder -- --publish always
