name: Publish

permissions: write-all

on:
    push:
        tags:
            - '*'

jobs:
    publish:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest, macos-13, macos-14]
                # os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v4

            - name: Install Node and NPM
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm

            - name: Install and build
              run: |
                  npm install
                  if [ "$RUNNER_OS" == "macOS" ]; then
                    npm install dmg-license
                  fi
                  npm run build
              shell: bash

            - name: Publish releases
              env:
                  # These values are used for auto updates signing
                  #   APPLE_ID: ${{ secrets.APPLE_ID }}
                  #   APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
                  #   CSC_LINK: ${{ secrets.CSC_LINK }}
                  #   CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
                  # This is used for uploading release assets to github
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # build for mac x64
                  if [ "$MATRIX_OS" == "macos-13" ]; then
                  npm exec electron-builder --mac dmg zip --x64 --publish always

                  # build for mac arm64
                  elif [ "$MATRIX_OS" == "macos-14" ]; then
                    npm exec electron-builder --mac dmg zip --arm64 --publish always

                  # build for windows/linux
                  else
                  npm exec electron-builder -- --publish always
                  fi
